version: "3.8"

services:
  db:
    image: postgres:17
    env_file: .env.docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 2s
      timeout: 3s
      start_period: 5s
      retries: 30
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data


  alembic:
    build: .
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.docker
    working_dir: /app
    command: ["alembic", "upgrade", "head"]
    restart: "no"
    volumes:
      - .:/app

  etl:
    build: .
    depends_on:
      db:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully
    env_file: .env.docker
    working_dir: /app
    command: ["python", "-m", "etl.main"]
    restart: unless-stopped
    volumes:
      - .:/app

volumes:
  pgdata:
